/**
 * Content Script — Widget CSS + HTML 模板
 *
 * 声明为 var 全局变量，供 content/widget-ui.js 使⽤。
 *
 * SVG 数字⼈规范源: assets/avatar-base.svg
 * 修改角色外观时：先改 avatar-base.svg，再将 zy- 前缀替换为 xb- 同步到这里。
 */
'use strict';

// ── Widget CSS ───────────────────────────────────────────
var __ZY_WIDGET_CSS__ = [
  ':host {',
  '  position: fixed !important;',
  '  bottom: 24px !important;',
  '  right: 32px !important;',
  '  z-index: 2147483647 !important;',
  '  display: block;',
  '  width: 90px;',
  '  height: 110px;',
  '  font-family: -apple-system, BlinkMacSystemFont, sans-serif;',
  '  pointer-events: none;',
  '  overflow: visible;',
  '}',
  '.widget-root {',
  '  position: relative;',
  '  width: 90px;',
  '  height: 110px;',
  '  pointer-events: none;',
  '  transform-origin: bottom right;',
  '  transition: opacity 0.22s ease, transform 0.22s ease;',
  '}',
  ':host(.collapsed) .widget-root {',
  '  opacity: 0;',
  '  pointer-events: none;',
  '  transform: scale(0.82);',
  '  visibility: hidden;',
  '}',
  ':host(.collapsed) .fan-layer,',
  ':host(.collapsed) .tinput-wrap {',
  '  pointer-events: none !important;',
  '}',
  '/* ── SVG ── */',
  '.xb-svg {',
  '  display: block;',
  '  overflow: visible;',
  '  cursor: grab;',
  '  touch-action: none;',
  '  user-select: none;',
  '  -webkit-user-select: none;',
  '  filter: drop-shadow(0 0 14px rgba(255,160,190,0.45));',
  '  animation: xb-float 3.5s ease-in-out infinite;',
  '  transition: filter 0.35s ease, opacity 0.3s ease, transform 0.3s ease;',
  '  pointer-events: none;',
  '}',
  '.xb-svg > * { pointer-events: visiblePainted; }',
  '.xb-svg.dragging { cursor: grabbing; animation: none; }',
  '.xb-svg.transitioning { opacity: 0; animation: none !important; }',
  '.xb-svg:active   { transform: scale(0.94); }',
  '',
  '@keyframes xb-float {',
  '  0%, 100% { transform: translateY(0px); }',
  '  50%       { transform: translateY(-6px); }',
  '}',
  '',
  '/* 轨道环 */',
  '#xb-halo {',
  '  transform-box: fill-box;',
  '  transform-origin: center;',
  '  animation: halo-spin 10s linear infinite;',
  '}',
  '@keyframes halo-spin {',
  '  from { transform: rotate(0deg); }',
  '  to   { transform: rotate(360deg); }',
  '}',
  '',
  '/* 眼部 */',
  '#xb-eye-l, #xb-eye-r {',
  '  transform-box: fill-box;',
  '  transform-origin: center;',
  '  animation: xb-blink 4s ease-in-out infinite;',
  '}',
  '#xb-eye-r { animation-delay: 0.15s; }',
  '@keyframes xb-blink {',
  '  0%, 82%, 100% { transform: scaleY(1); }',
  '  90%            { transform: scaleY(0.06); }',
  '}',
  '',
  '/* ── idle ── */',
  '.xb-svg.idle #xb-glow {',
  '  animation: xb-glow-pulse 4s ease-in-out infinite;',
  '}',
  '@keyframes xb-glow-pulse {',
  '  0%, 100% { opacity: 0.6; }',
  '  50%       { opacity: 1; }',
  '}',
  '.xb-svg.listening {',
  '  animation: xb-listen 0.5s ease-in-out infinite;',
  '  filter: drop-shadow(0 0 18px rgba(245,158,11,0.70));',
  '}',
  '.xb-svg.listening #xb-halo { animation: halo-spin 1.5s linear infinite; }',
  '@keyframes xb-listen {',
  '  0%, 100% { transform: translateY(-3px) scale(1.02); }',
  '  50%       { transform: translateY(-9px) scale(1.05); }',
  '}',
  '.xb-svg.listening #xb-eye-l,',
  '.xb-svg.listening #xb-eye-r { animation: none; transform: scaleY(1.3); }',
  '.xb-svg.listening #xb-cheek-l,',
  '.xb-svg.listening #xb-cheek-r { animation: xb-cheek 0.5s ease-in-out infinite alternate; }',
  '',
  '/* ── thinking ── */',
  '.xb-svg.thinking {',
  '  animation: xb-think 1.4s ease-in-out infinite;',
  '  filter: drop-shadow(0 0 18px rgba(139,92,246,0.70));',
  '}',
  '.xb-svg.thinking #xb-halo { animation: halo-pulse-ring 1.4s ease-in-out infinite; }',
  '@keyframes halo-pulse-ring {',
  '  0%, 100% { transform: scale(1) rotate(0deg); }',
  '  50%       { transform: scale(1.1) rotate(180deg); }',
  '}',
  '@keyframes xb-think {',
  '  0%, 100% { transform: translateY(0) rotate(-3deg); }',
  '  50%       { transform: translateY(-5px) rotate(3deg); }',
  '}',
  '.xb-svg.thinking #xb-eye-l,',
  '.xb-svg.thinking #xb-eye-r {',
  '  animation: xb-eye-scan 1.4s ease-in-out infinite;',
  '  transform-box: fill-box; transform-origin: center;',
  '}',
  '@keyframes xb-eye-scan {',
  '  0%, 100% { transform: translateX(-3px) scaleY(0.6); }',
  '  50%       { transform: translateX(3px)  scaleY(0.6); }',
  '}',
  '',
  '/* ── speaking ── */',
  '.xb-svg.speaking {',
  '  animation: xb-speak-hop 0.45s ease-in-out infinite;',
  '  filter: drop-shadow(0 0 18px rgba(16,185,129,0.70));',
  '}',
  '.xb-svg.speaking #xb-halo { animation: halo-spin 0.8s linear infinite; }',
  '@keyframes xb-speak-hop {',
  '  0%, 100% { transform: translateY(0); }',
  '  45%       { transform: translateY(-7px); }',
  '}',
  '.xb-svg.speaking #xb-mouth-normal { opacity: 0; }',
  '.xb-svg.speaking #xb-mouth-open {',
  '  opacity: 1;',
  '  animation: xb-mouth 0.38s ease-in-out infinite;',
  '}',
  '@keyframes xb-mouth {',
  '  0%, 100% { transform: scaleY(0.7); transform-box: fill-box; transform-origin: center top; }',
  '  50%       { transform: scaleY(1.3); transform-box: fill-box; transform-origin: center top; }',
  '}',
  '.xb-svg.speaking #xb-cheek-l,',
  '.xb-svg.speaking #xb-cheek-r { animation: xb-cheek 0.45s ease-in-out infinite alternate; }',
  '',
  '@keyframes xb-cheek {',
  '  from { filter: drop-shadow(0 0 3px #ffb3c1); }',
  '  to   { filter: drop-shadow(0 0 8px #ff7090); }',
  '}',
  '',
  '/* ── error ── */',
  '.xb-svg.error {',
  '  animation: xb-shake 0.4s ease-in-out;',
  '  filter: drop-shadow(0 0 18px rgba(239,68,68,0.70));',
  '}',
  '.xb-svg.error #xb-halo { animation: none; opacity: 0; }',
  '.xb-svg.error #xb-eye-l,',
  '.xb-svg.error #xb-eye-r {',
  '  animation: none;',
  '  transform: scaleY(0.1);', // squint eyes
  '}',
  '.xb-svg.error #xb-mouth-normal { opacity: 0; }',
  '.xb-svg.error #xb-mouth-open {',
  '  opacity: 1;',
  '  fill: #ef4444;',
  '}',
  '@keyframes xb-shake {',
  '  0%, 100% { transform: translateX(0); }',
  '  20% { transform: translateX(-6px) rotate(-5deg); }',
  '  40% { transform: translateX(6px) rotate(5deg); }',
  '  60% { transform: translateX(-4px) rotate(-3deg); }',
  '  80% { transform: translateX(4px) rotate(3deg); }',
  '}',
  '',
  '/* ── 扇形菜单 ── */',
  '.fan-layer {',
  '  position: absolute;',
  '  inset: 0;',
  '  pointer-events: none;',
  '}',
  '.fbtn {',
  '  position: absolute;',
  '  width: 44px; height: 44px;',
  '  top: 56px; left: 22px;',
  '  border-radius: 50%;',
  '  border: none;',
  '  cursor: pointer;',
  '  font-size: 18px;',
  '  display: flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  color: white;',
  '  pointer-events: none;',
  '  transform: scale(0);',
  '  opacity: 0;',
  '  transition: transform 0.28s cubic-bezier(0.34,1.56,0.64,1), opacity 0.22s ease;',
  '  will-change: transform, opacity;',
  '  box-shadow: 0 3px 10px rgba(0,0,0,0.4);',
  '}',
  '.fbtn:hover  { background: linear-gradient(135deg,#ffd0dc,#f0a0b8) !important; color: #8b3a50 !important; filter: none; }',
  '.fbtn:active { filter: brightness(0.90); }',
  '.fan-layer.open .fbtn { pointer-events: auto; }',
  '',
  '.fan-layer.open .fbtn.mic {',
  '  transform: translate(2px, -110px) scale(1);',
  '  opacity: 1;',
  '}',
  '.fan-layer.open .fbtn.txt {',
  '  transform: translate(-59px, -71px) scale(1);',
  '  opacity: 1;',
  '  transition-delay: 0.05s;',
  '}',
  '.fan-layer.open .fbtn.cfg {',
  '  transform: translate(-71px, -14px) scale(1);',
  '  opacity: 1;',
  '  transition-delay: 0.10s;',
  '}',
  '.fan-layer.open .fbtn.hide {',
  '  transform: translate(-48px, 44px) scale(1);',
  '  opacity: 1;',
  '  transition-delay: 0.15s;',
  '}',
  '',
  '.fbtn.mic { background: linear-gradient(135deg,#fffef8,#f0e4d4); color: #7a5040; }',
  '.fbtn.mic.recording {',
  '  background: linear-gradient(135deg,#ef4444,#dc2626);',
  '  color: white;',
  '  animation: btn-recording 0.8s ease-in-out infinite;',
  '}',
  '.fbtn.txt { background: linear-gradient(135deg,#fffef8,#f0e4d4); color: #7a5040; }',
  '.fbtn.cfg { background: linear-gradient(135deg,#fffef8,#f0e4d4); color: #7a5040; }',
  '.fbtn.hide { background: linear-gradient(135deg,#fffef8,#f0e4d4); color: #7a5040; }',
  '',
  '/* ── 步骤进度徽标 ── */',
'.step-badge {',
'  position: absolute;',
'  top: -4px;',
'  right: -6px;',
'  min-width: 22px;',
'  height: 22px;',
'  padding: 0 6px;',
'  border-radius: 11px;',
'  background: #3b82f6;',
'  color: white;',
'  font-size: 11px;',
'  font-weight: 700;',
'  line-height: 22px;',
'  text-align: center;',
'  z-index: 10;',
'  pointer-events: none;',
'  transform: scale(0);',
'  opacity: 0;',
'  transition: transform 0.25s cubic-bezier(0.34,1.56,0.64,1), opacity 0.2s ease;',
'  box-shadow: 0 2px 6px rgba(59,130,246,0.4);',
'}',
'.step-badge.visible {',
'  transform: scale(1);',
'  opacity: 1;',
'}',
'.step-badge.done {',
'  background: #10b981;',
'  box-shadow: 0 2px 6px rgba(16,185,129,0.4);',
'}',
'',
'/* ── 文字输入框 ── */',
  '.tinput-wrap {',
  '  position: absolute;',
  '  bottom: 112px;',
  '  right: 0;',
  '  width: 210px;',
  '  opacity: 0;',
  '  pointer-events: none;',
  '  transform: translateY(8px);',
  '  transition: opacity 0.22s, transform 0.22s;',
  '}',
  '.tinput-wrap.visible {',
  '  opacity: 1;',
  '  pointer-events: auto;',
  '  transform: translateY(0);',
  '}',
  '.tinput {',
  '  width: 100%;',
  '  box-sizing: border-box;',
  '  padding: 9px 14px;',
  '  border-radius: 14px;',
  '  border: 2px solid #3b82f6;',
  '  background: #0f172a;',
  '  color: #f8fafc;',
  '  font-size: 13px;',
  '  font-family: -apple-system, BlinkMacSystemFont, sans-serif;',
  '  outline: none;',
  '  box-shadow: 0 4px 16px rgba(0,0,0,0.45);',
  '  resize: none;',
  '  line-height: 1.45;',
  '  max-height: 120px;',
  '  overflow-y: auto;',
  '  scrollbar-width: thin;',
  '}',
  '.tinput::placeholder { color: #475569; }',
  '.tinput:focus { border-color: #60a5fa; }',
  '',
  '@media (prefers-color-scheme: light) {',
  '  .tinput {',
  '    background: #ffffff;',
  '    color: #1e293b;',
  '    box-shadow: 0 4px 16px rgba(0,0,0,0.12);',
  '  }',
  '  .tinput::placeholder { color: #94a3b8; }',
  '  .tinput-wrap { background: transparent; }',
  '}'
].join('\n');

// ── Widget HTML ──────────────────────────────────────────
// SVG 数字人规范源: assets/avatar-base.svg
// 修改角色外观时：先改 avatar-base.svg，再将 zy- 前缀替换为 xb- 同步到这里。
var __ZY_WIDGET_HTML__ = [
  '<div class="widget-root">',
  '  <div class="fan-layer" id="fan-layer">',
  '    <button class="fbtn mic" id="fbtn-mic" title="长按录音">🎤</button>',
  '    <button class="fbtn txt" id="fbtn-txt" title="文字输入">✏️</button>',
  '    <button class="fbtn cfg" id="fbtn-cfg" title="打开设置面板">⚙️</button>',
  '    <button class="fbtn hide" id="fbtn-hide" title="隐藏数字人">−</button>',
  '    <div class="step-badge" id="step-badge"></div>',
  '  </div>',
  '  <!--',
  '    SVG 来源: assets/avatar-base.svg',
  '    修改角色外观：先改那文件，再将 zy- → xb- 替换后复制到这里',
  '  -->',
  '  <svg class="xb-svg idle" id="pika" viewBox="0 0 100 120" width="86"',
  '       overflow="visible" xmlns="http://www.w3.org/2000/svg">',
  '    <defs>',
  '      <radialGradient id="xb-head-g" cx="38%" cy="32%" r="65%">',
  '        <stop offset="0%"   stop-color="#fffef8"/>',
  '        <stop offset="55%"  stop-color="#f8ece0"/>',
  '        <stop offset="100%" stop-color="#e8d0bc"/>',
  '      </radialGradient>',
  '      <radialGradient id="xb-body-g" cx="40%" cy="30%" r="65%">',
  '        <stop offset="0%"   stop-color="#fff4f0"/>',
  '        <stop offset="55%"  stop-color="#f5dcd8"/>',
  '        <stop offset="100%" stop-color="#e0b8b4"/>',
  '      </radialGradient>',
  '      <radialGradient id="xb-eye-g" cx="30%" cy="28%" r="66%">',
  '        <stop offset="0%"   stop-color="#c8f0ff"/>',
  '        <stop offset="50%"  stop-color="#3098d8"/>',
  '        <stop offset="100%" stop-color="#0860a8"/>',
  '      </radialGradient>',
  '      <radialGradient id="xb-foot-g" cx="40%" cy="35%" r="65%">',
  '        <stop offset="0%"   stop-color="#ffd0dc"/>',
  '        <stop offset="100%" stop-color="#f0a0b8"/>',
  '      </radialGradient>',
  '    </defs>',
  '    <ellipse cx="50" cy="32" rx="40" ry="40" fill="rgba(255,180,200,0.07)"/>',
  '    <g id="xb-halo">',
  '      <circle cx="50" cy="32" r="36" fill="none"',
  '              stroke="#ffb0c8" stroke-width="1.8"',
  '              stroke-dasharray="11 5" stroke-linecap="round" opacity="0.80"/>',
  '    </g>',
  '    <circle cx="50" cy="32" r="30" fill="url(#xb-head-g)"/>',
  '    <ellipse cx="41" cy="18" rx="10" ry="6"',
  '             fill="rgba(255,255,255,0.50)" transform="rotate(-12,41,18)"/>',
  '    <ellipse cx="50" cy="34" rx="21" ry="19" fill="#fff8f0"/>',
  '    <g id="xb-eye-l">',
  '      <ellipse cx="42" cy="31" rx="6.5" ry="7"   fill="url(#xb-eye-g)"/>',
  '      <circle  cx="39"   cy="28"   r="3.8" fill="rgba(255,255,255,0.92)"/>',
  '      <circle  cx="45.5" cy="34.5" r="1.6" fill="rgba(255,255,255,0.38)"/>',
  '    </g>',
  '    <g id="xb-eye-r">',
  '      <ellipse cx="58" cy="31" rx="6.5" ry="7"   fill="url(#xb-eye-g)"/>',
  '      <circle  cx="55"   cy="28"   r="3.8" fill="rgba(255,255,255,0.92)"/>',
  '      <circle  cx="61.5" cy="34.5" r="1.6" fill="rgba(255,255,255,0.38)"/>',
  '    </g>',
  '    <ellipse id="xb-cheek-l" cx="32" cy="37" rx="7" ry="4.5" fill="#ffb8c8" opacity="0.75"/>',
  '    <ellipse id="xb-cheek-r" cx="68" cy="37" rx="7" ry="4.5" fill="#ffb8c8" opacity="0.75"/>',
  '    <path id="xb-mouth-normal" d="M 44,44 Q 50,49 56,44"',
  '          fill="none" stroke="#d08878" stroke-width="1.7" stroke-linecap="round"/>',
  '    <g id="xb-mouth-open" opacity="0">',
  '      <path d="M 44,44 Q 50,50 56,44" fill="#d08070"/>',
  '      <ellipse cx="50" cy="47" rx="5" ry="2.8" fill="#b85050"/>',
  '    </g>',
  '    <path d="M 39,62 C 28,64 14,70 14,82',
  '             C 14,95 26,104 50,104',
  '             C 74,104 86,95 86,82',
  '             C 86,70 72,64 61,62 Z"',
  '          fill="url(#xb-body-g)"/>',
  '    <ellipse cx="44" cy="80" rx="11" ry="13" fill="rgba(255,255,255,0.30)"/>',
  '    <ellipse cx="9"  cy="76" rx="13" ry="8" fill="url(#xb-body-g)" transform="rotate(-22,9,76)"/>',
  '    <ellipse cx="91" cy="76" rx="13" ry="8" fill="url(#xb-body-g)" transform="rotate(22,91,76)"/>',
  '    <ellipse cx="37" cy="110" rx="13" ry="8" fill="url(#xb-foot-g)"/>',
  '    <ellipse cx="63" cy="110" rx="13" ry="8" fill="url(#xb-foot-g)"/>',
  '    <ellipse cx="34" cy="107" rx="5"  ry="3" fill="rgba(255,255,255,0.40)"/>',
  '    <ellipse cx="60" cy="107" rx="5"  ry="3" fill="rgba(255,255,255,0.40)"/>',
  '  </svg>',
  '  <div class="tinput-wrap" id="tinput-wrap">',
  '    <textarea class="tinput" id="tinput" rows="1" placeholder="输入指令，回车发送"></textarea>',
  '  </div>',
  '</div>'
].join('\n');
